[[redirects]]
    from = "/*"
    to = "/static/errors/404.html"
    status = 404
	
[[redirects]]
    from = "/*"
    to = "/static/errors/403.html"
    status = 403
	
[[redirects]]
    from = "/*"
    to = "/static/errors/500.html"
    status = 500